"""
Daily Spark — one short motivational message generated by Claude Haiku.
Cached in the frontend (localStorage), so this endpoint is called at most
once per day per client.
"""
import logging
from datetime import date

import anthropic
from fastapi import APIRouter, HTTPException, Request

from app.config import get_settings
from app.limiter import limiter

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/api/spark", tags=["spark"])

_PROMPT = (
    "Write one short message for Creator. She is a beauty creator in Toronto but this message "
    "is not about Instagram or metrics. It is about life. "
    "Think: the kind of thing a wise, warm best friend texts you on a random Tuesday that makes you stop and smile. "
    "Sometimes philosophical, sometimes poetic, sometimes just quietly true. Always real, never cheesy. "
    "It can be about growth, love, time, rest, courage, beauty in the everyday, or simply being a woman in the world. "
    "Max 2 sentences. Short and beautiful. "
    "English only. No hashtags. No emojis. Never use dashes (— or -). Use periods instead."
)


@router.get("/daily")
@limiter.limit("10/hour")
async def daily_spark(request: Request):
    settings = get_settings()
    try:
        client = anthropic.Anthropic(api_key=settings.anthropic_api_key)
        response = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=120,
            messages=[{"role": "user", "content": _PROMPT}],
        )
        message = response.content[0].text.strip()
        return {"message": message, "date": date.today().isoformat()}
    except Exception as exc:
        logger.error("daily_spark failed: %s", exc)
        raise HTTPException(status_code=502, detail="Failed to generate spark") from exc
